### PR TITLE
Add Haraguchi et al.

### PR DESCRIPTION
**Pull request by naoto0804**
Hi, thank you for hosting an excellent repo! I would like to include our recent work.

### CODE REVIEW

**Comment by sahilg06** [comment]
Thank you @naoto0804 for PR.

**Comment by naoto0804** [comment]
By the way congratulations on the Design-o-meter's acceptance to WACV2025!

**Comment by sahilg06** [comment]
Thank you @naoto0804!!

**Comment by sahilg06** [comment]
Also, I have followed your several works like FlexDM, LayoutDM etc. Thanks for doing great work in the design/layout generation field. 
A lot of work is going for graphic design generation, but evaluation of graphic designs hasn't been explored to that extent. I hope this field also get evolved in coming time.

**Pull request merged**
